[project]
name = "test_pdm"
version = "0.0.1"
description = "sample project to test pdm"
authors = [
    {name = "Ning Wang", email = "nyngwang@gmail.com"},
]
dependencies = [
    "requests>=2.27.1",
    "flask>=2.0.3",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[project.urls]
Homepage = ""
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
